version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: password
      POSTGRES_DB: booking
    ports:
      - 15432:5432
    expose:
      - "5432"
    volumes:
      - ../db/migrations:/docker-entrypoint-initdb.d